sudo: false
env:
  global:
  - LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libgfortran.so.3
  - secure: HC56kqcyplnfsHFZpM122GVdG8j0b6M1uexIJKVCpy8YS6u7ooS8Oh9jp6OxDyg47OtGJGRPeGvQJ2bMuKhbNz+3YHNxf08AJVApwPq+25PpfGedMWMgmZI42zAzN6RYVUDjYEZb3Y52j4Kw8UaFwfdxoPVFhTiRCgr054laZFc=
addons:
  apt:
    packages:
    - gfortran
language: python
deploy:
  provider: pypi
  user: joseph.hardin
  password:
    secure: RXHwdpCq99AiCzO+uM8PFGUAP382tGEtPS0QnlbaAWN+6sCnHfpPyy9YClsv5N+PhIqKnHuX5O3nx/XlQVyaHMqbUxzReHYPvJFbbqNErlZ36DXNYxVWkqUgnNz1EbGxKQ08oTmBlTym138umsK1Wqu5+Mv913QaSQa6g1D6Kl4=
  on:
      tags: true

matrix:
  include:
  - python: '2.7'
    env:
    - PYTHON_VERSION="2.7"
    - NOSE_ARGS="-v --no-skip --with-cov --cov pydsd pydsd"
    - COVERALLS="true"
  - python: '3.4'
    env:
    - PYTHON_VERSION="3.4"
    - NOSE_ARGS="-v --no-skip --with-cov --cov pydsd pydsd"
    - COVERALLS="true"
  - python: '3.5'
    env:
    - PYTHON_VERSION="3.5"
    - NOSE_ARGS="-v --no-skip --with-cov --cov pydsd pydsd"
    - COVERALLS="true"
  - python: '3.6'
    env:
    - PYTHON_VERSION="3.6"
    - NOSE_ARGS="-v --no-skip --with-cov --cov pydsd pydsd"
    - COVERALLS="true"
  - python: '3.6'
    env:
    - PYTHON_VERSION="3.6"
    - NOSE_ARGS="-v --no-skip --with-cov --cov pydsd pydsd"
    - COVERALLS="true"
    - DOC_BUILD="true"
before_install:
- pip install pytest pytest-cov
- pip install coveralls
install: source continuous_integration/install.sh
script: eval xvfb-run nosetests $NOSE_ARGS
after_success:
- coveralls
- if [[ "$DOC_BUILD" == "true" ]]; then cd $TRAVIS_BUILD_DIR; source continuous_integration/build_docs.sh;
  fi
